language: python
dist: xenial
python:
- nightly
- 3.8-dev
- 3.7-dev
- 3.7
- 3.6
- 3.5
- pypy3.5
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: eghuro
  password:
    secure: QegdsmxfB3X0v2zZxlJHGYDM+P8LMv176XeTGI4gSr3J5VdjtiUbQCRFIpJEkQMGfOxMvAqBDO8FyzCFY1qrWv2wjktYxoRq7ioriX/+26HqZ0poB7jgoSpZY+Yje1qDshDiFeu9c5b9cUAie9ZaJXMzRZDPyxEeAgjLGezj91RBYzG1owOfxSaj9gwEURoqsrEGQpJXJBAm6VKSPQYvqivC6wy+zzVyXpXVseFgfpaQQUntysff1ajRB29Sq5XYTT+A0FSK09/c3bIgRrInlpTK7t8+sPd+sdHIO4Op/T5xsprAqknOV1jAOMRSreQcgMnTByn/WbZSaFh5oN7SsmP9KGMmnW+faJZ36ThGXcrZvRxmLuUEkg5PJqv7oNjySc/SSn1tPI21RnJZNDTlqyP7lrfgV9SPm4Dk8bZ9uJyN5NKZTJ/xt9PvajDTcOLEsbeTUnWVKQD6UKAG8aiUzYHqJ6FfDxPv9HrB7zlXDJm0zFi1pqIpCObGvpvdp9uuXJlc3IlI3MthuoAbzLuxbliHXFKhv2VafUd9EeI7EtpXTRNF1Kd3twYM1XfhB6GvUQVN2RGhO8cNnsIDbPykoqkFS2cW+0KapUEJmOtZILhSN/r4Jq+BNqCLGY6cAbFm10fNPwQR3sgDYfn7RiY/VRHzvnzOlTv32cxeF4O3Jqw=
  on:
    tags: true
    repo: eghuro/atenvironment
    python: 3.6
